### PR TITLE
fix: remove deprecated use of vim.tbl_add_reverse_lookup

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by phush0** [comment]
merge pls msg is anoying

**Comment by hrsh7th** [comment]
thank you!

**Comment by AThePeanut4** [comment]
@hrsh7th @lewis6991 This iterates while adding new keys, which doesn't seem to cause any issues but is technically undefined afaik. `vim.tbl_add_reverse_lookup` uses `vim.tbl_keys` to get around this issue.

**Comment by lewis6991** [comment]
Yes, I just realised that. Hopefully this doesn't cause an issue but fixing should be easy if it does.

**Comment by yioneko** [comment]
I could confirm this causes some kv pairs not added on my end. I added a print statement just after the loop assignments:
```diff
diff --git a/lua/cmp/types/lsp.lua b/lua/cmp/types/lsp.lua
index 65d6301..2dfa192 100644
--- a/lua/cmp/types/lsp.lua
+++ b/lua/cmp/types/lsp.lua
@@ -205,6 +205,7 @@ lsp.CompletionItemKind = {
 for k, v in pairs(lsp.CompletionItemKind) do
   lsp.CompletionItemKind[v] = k
 end
+vim.print(lsp.CompletionItemKind)
 
 ---@class lsp.internal.CompletionItemDefaults
 ---@field public commitCharacters? string[]
```

And occasionally it shows that some pairs are not correctly added:

image

`Reference` at index 18 is missing this time. The missing kind is random, and I've seen kinds `Function` and `Text` could also disappear in completion window.

**Pull request merged**
