### PR TITLE
Avoid expr mapping message

### PR DESCRIPTION
**Pull request by hrsh7th**

### CODE REVIEW

**Comment by hrsh7th** [comment]
@wookayin Sorry. I've re-fix the keymap implementation. Could you test this...?

**Comment by axieax** [comment]
Hi, for some reason, this commit breaks command mode completion for me. I'm on nvim version 6.1 :(

**Comment by hrsh7th** [comment]
Sorry. I've fixed. (It's really strange, but I forgot that cmdline key mapping doesn't work properly with silent enabled.

**Comment by axieax** [comment]
image

Seems like the issue is still here for some reason :p

**Comment by axieax** [comment]
Works now thanks :)

**Comment by wookayin** [comment]
@hrsh7th Fortunately, I have no issues with those changes and everything works fine. Thank you.

**Pull request merged**
