### PR TITLE
Mark ConfigSchema fields as optional to prevent LSP warnings

### PR DESCRIPTION
**Pull request by HNegus**
The Lua Language Server will show a warning when calling `cmp.setup` because the table fields are not marked as optional.

### CODE REVIEW

**Comment by wookayin** [comment]
Then all the internal codes that depend on `cmp.ConfigSchema` should do (unnecessary) nil check, right? I think a better solution might be have a **different** type than `cmp.ConfigSchema` that is used for `cmp.setup` only.

**Comment by HNegus** [comment]
I believe the type is used in just a few places, so wouldn't the impact be very limited?

**Comment by hrsh7th** [comment]
Sorry. I'd merged another PR. Thank you.

**Comment by wookayin** [comment]
Fixed in #1723

**Pull request closed without merging**
