### PR TITLE
README.md: don't set 'completeopt'

### PR DESCRIPTION
**Pull request by Prince213**
See https://github.com/hrsh7th/nvim-cmp/discussions/941.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Hmm... nvim-cmp looks at `completeopt` in its implementation.
But I think it can be removed.

**Comment by CalebDW** [comment]
I'm confused...does it need to be set or not? I have it set to:
```
vim.opt.completeopt = { 'menuone', 'longest', 'preview' }
```

**Comment by hrsh7th** [comment]
I recommend to set `set completeopt=menu,menuone,noselect`.
because it makes general completion behavior.
if you hope to use native completion menu with omnifunc via `<C-x><C-o>` etc, it might be help.

**Comment by Prince213** [comment]
So nvim-cmp is not related with the builtin [ins-completion](https://neovim.io/doc/user/insert.html#ins-completion), but can be used from it, and ['completeopt'](https://neovim.io/doc/user/options.html#'completeopt') is only for that specific use case, which means it's not needed otherwise.

If that's the case, maybe this could be mentioned in README.md.

**Pull request merged**
