### PR TITLE
Add mapping example to README

### PR DESCRIPTION
**Pull request by uga-rosa**
A mapping example that was frequently asked about has been added to README.md.
Sorry, but I don't use vsnip, so if you prefer that, please adjust accordingly.

### CODE REVIEW

**Comment by mortezadadgar** [comment]
you could have use `cmp.utils.keymap.t` instead of defining a new function

**Comment by uga-rosa** [comment]
Oh, thx!

**Comment by hrsh7th** [comment]
Ah! Sorry. I  want to expose only`require('cmp')` as public API. So please don't use `reuqire('cmp.utils.*')`

**Comment by hrsh7th** [comment]
LGTM! Thank you!

**Pull request merged**
