### PR TITLE
Bottom up mode for custom menu

### PR DESCRIPTION
**Pull request by tzachar**
When in command line mode, the custom entry window opens up to an
unexpected height, depending on the current count of completion items.
The above makes it hard to anticipate where to look at, and makes life a bit
harder.

This patch adds an option to open the custom entries view in a bottom up
mode, and flips the regular behaviour of next/prev entry in this mode.
Setup is as easy as:

```
cmp.setup.cmdline(':', {
  view = {
    entries = {name = 'custom', selection_order = 'near_cursor' } 
  }
}
```

### CODE REVIEW

**Comment by tzachar** [comment]
@hrsh7th 
Any chance of merging this?
10x

**Comment by hrsh7th** [comment]
I think this must be smarter because the current option is only worth cmdline-completion.

For example, we can determine the direction via `the window is upper the cursor or not`.

I don't imagine the suitable option name but it should be changed, I think. e.g.: `selection_order = 'top_down' | 'near_cursor'`.

**Comment by tzachar** [comment]
I like your idea.
Will try to implement.

**Comment by hrsh7th** [comment]
Please consider the suitable option name :)

**Comment by tzachar** [comment]
sure

**Comment by tzachar** [comment]
@hrsh7th 
I think this last commit fixes all issues.
If you have nothing else, I would appreciate if you can merge this.
Cheers.

**Comment by max397574** [comment]
Could you share an image or a gif of how this will look like?

**Comment by tzachar** [comment]
Peek 2022-03-30 15-05

**Comment by tzachar** [comment]
@hrsh7th 
Apologies if im pushing, but this has been ready for a while now.
Do you intend to merge?

**Comment by hrsh7th** [comment]
LGTM.
I've checked the behavior. I don't like this behavior but someone might like this may be.

**Comment by tzachar** [comment]
Thank you.
Ill add a wiki for this feature.

**Comment by rignet-bicteg** [comment]
This PR broke command line autocompletion from Vim proper for me. When I open vim and do :e <Tab> I get an `I^`.

**Comment by hrsh7th** [comment]
I can't reproduce. How do you determine the commit that broke the behavior?

**Comment by tzachar** [comment]
I think this is something different. nvim now differentiats between <c-tab>
and <c-I>.

**Comment by cinuor** [comment]
same to me, Tab in command line output like this
image

Tab and S-Tab mapped by cmp，but i do not set those in my cmp mapping config

**Comment by hrsh7th** [comment]
This is not related to this PR. I've fixed it in latest main.

**Pull request merged**
