### PR TITLE
ci: add release workflow to publish new tags to LuaRocks

### PR DESCRIPTION
**Pull request by mrcjkb**
NOTE: This requires a LUAROCKS_API_KEY.
See also the [luarocks-tag-release README](https://github.com/nvim-neorocks/luarocks-tag-release#prerequisites).

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you for your cooperation.

I would like to know the benefits of registering nvim-cmp with LuaRocks.

**Comment by mrcjkb** [comment]
> Thank you for your cooperation.
> 
> I would like to know the benefits of registering nvim-cmp with LuaRocks.

Oh, sorry I forgot to update the description.
I wrote a [blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html) yesterday that should contain all the info :)

**Comment by hrsh7th** [comment]
Thank you for the detailed information.

I agree with that story, and it seems fine to register nvim-cmp with LuaRocks for the time being.

So it's safe to merge.
I will check the operation and the code.

**Comment by mrcjkb** [comment]
Thanks for supporting this.

**Pull request merged**
