### PR TITLE
docs!: improve the instructions to follow breaking changes (#231)

### PR DESCRIPTION
**Pull request by Kjir**
Improve the README instruction on where to find breaking changes. Included a suggestion to subscribe to the github issue to get notified about changes.

### CODE REVIEW

**Comment by runiq** [comment]
I recommend making this PR a breaking change by adding `feat!` in front of the commit message, so Packer emphasizes it in its status display (https://github.com/hrsh7th/nvim-cmp/issues/896#issuecomment-1099035112)

**Comment by Kjir** [comment]
I'm confused: I agree with the comment in general, but this PR isn't a breaking change

**Comment by runiq** [comment]
I know it's not, but by saying it is, you'll make it more visible

**Comment by Kjir** [comment]
I updated the commit to include pointers to the issue as well, so hopefully people will gain knowledge about this issues and can subscribe to it.

**Comment by hrsh7th** [comment]
LGTM. Thank you for your good contribution!

**Pull request merged**
