### PR TITLE
fix(feedkeys): resolve issue with some copilot completions

### LINKED ISSUE #1560: Error of  : start_col out of bounds. Extra characters at the end of completions.
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

Unfortunately, I cannot reliably reproduce this. It happens randomly, and I have to close and reopen nvim.

### Description

I am having the same issue as described in issue https://github.com/hrsh7th/nvim-cmp/issues/1097 but that one said to open a new issue.

Sometimes I will start to notice that completions will have extra characters at the end. Today was the first time that I recall seeing an actual error, which can be seen below.

Example:
I start to type something, and at the end of the completion, it should end with `");`  but it ends with `");");`. Yesterday, I noticed that it was doing this, but with a newline as well.

Ex.
Expected this:
```
let whatever = whatever("whatever");
```
Got this:
```
let whatever = whatever("whatever");
);
```
Below are my version numbers, as well as the actual error message that appeared this time, which prompted my searching and coming across the issue mentioned above.

Versions
```
NVIM v0.9.0-dev-554+g6f25623e7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

● nvim-cmp 0.7ms  lsp-zero.nvim
    dir    /home/mosthated/.local/share/nvim/lazy/nvim-cmp
    url    https://github.com/hrsh7th/nvim-cmp
    branch main
    commit 1cad30f
    readme README.md
    help   |nvim-cmp|
```

```
Error  04:58:19 PM msg_show.lua_error E5108: Error executing lua ...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:383: start_col out of bounds
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:383: in function <...sthated/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:371>
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function <...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:45>
```

### Steps to reproduce

Unfortunately, it is seemingly pretty random. I am not sure how to forcefully reproduce it. So far, I have only noticed it in Rust, but at the same time, I have only really been writing Rust the last few weeks.

### Expected behavior

No error or extra characters in completions 

### Actual behavior

Error and extra characters in completions 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tris203**
This seems to fix #1560 in my limited testing. It would be great if anyone else can test it and see if any other issues arise.
and https://github.com/zbirenbaum/copilot-cmp/issues/79

At the very least, we should include the pcall to stop it from crashing cmp entirely in the event of a bad completion,

This is required after neovim deprecations here:
https://github.com/neovim/neovim/pull/24350

### CODE REVIEW

**Comment by eli-front** [comment]
This seems to reduce the number of times I see this error, but I still got a `.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:394: Invalid 'start_col': out of range` when using this PR. Struggling to reproduce consistently, but will post here if I figure something out

**Comment by tris203** [comment]
> This seems to reduce the number of times I see this error, but I still got a `.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:394: Invalid 'start_col': out of range` when using this PR. Struggling to reproduce consistently, but will post here if I figure something out

Interesting. What language are you writing?
I also assume with this PR, that it didn't crash cmp completely? so you should be able to undo and reproduce the error over and over again

**Comment by eli-front** [comment]
> > This seems to reduce the number of times I see this error, but I still got a `.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:394: Invalid 'start_col': out of range` when using this PR. Struggling to reproduce consistently, but will post here if I figure something out
> 
> Interesting. What language are you writing? I also assume with this PR, that it didn't crash cmp completely? so you should be able to undo and reproduce the error over and over again

I was using typescript. Here's my `nvim-cmp` config
```
return {
  "https://github.com/tris203/nvim-cmp",
  commit = "ab4cb2a3f5c439c5a4b4e92f92b50df0164f7713",
  event = "InsertEnter",
  config = function()
    local cmp = require("cmp")
    cmp.setup({
      sources = {
        { name = "copilot" },
        { name = "nvim_lsp" },
        { name = "luasnip" }, -- snippets
        { name = "buffer" },  -- text within current buffer
        { name = "path" },    -- file system paths
      },
      mapping = cmp.mapping.preset.insert({
        ['<CR>'] = cmp.mapping.confirm({
          behavior = cmp.ConfirmBehavior.Replace,
          select = false,
        }),
        ['<C-j>'] = cmp.mapping.select_next_item(),
        ['<C-k>'] = cmp.mapping.select_prev_item(),
      })
    })
  end,
}
```

**Review by hrsh7th — APPROVED** [review]
thank you

**Pull request merged**
