### PR TITLE
feat(view): add api get_selected_index

### PR DESCRIPTION
**Pull request by uga-rosa**
API to get the number of the currently selected candidate, which can be combined with get_entries to find out "what are the entries above and below".

### CODE REVIEW

**Comment by hrsh7th** [comment]
LGTM.

**Comment by monheimx9** [comment]
> LGTM.

```
Error  19:23:09 msg_show.emsg E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value)
stack traceback:
	.../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: in function 'select_next_item'
	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:224: in function 'select_next_item'
	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:146: in function 'select_next_item'
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:48: in function 'on_keymap'
	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
	....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
```
While performing <C-n> on the selection
Do you think this is related to this PR or I am looking at the wrong place?

Should I open an issue or can I let a message on the thread?

**Comment by curiousignite** [comment]
> > LGTM.
> 
> ```
> Error  19:23:09 msg_show.emsg E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value)
> stack traceback:
> 	.../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: in function 'select_next_item'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:224: in function 'select_next_item'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:146: in function 'select_next_item'
> 	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:48: in function 'on_keymap'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
> 	....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
> ```
> 
> While performing <C-n> on the selection Do you think this is related to this PR or I am looking at the wrong place?
> 
> Should I open an issue or can I keep commenting on this thread?
> 
> Edit: I'm using LazyVim distro and haven't changed anything related to cmp on my config
> 
> Edit2: Confirmation: reverting back to [7e348da](https://github.com/hrsh7th/nvim-cmp/commit/7e348da6e5085ac447144a2ef4b637220ba27209) cleared the issue

I was just editing my config and trying to figure out where did I f up. This saved hours, thank you.

**Comment by 0xDmtri** [comment]
> > > LGTM.
> > 
> > 
> > ```
> > Error  19:23:09 msg_show.emsg E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value)
> > stack traceback:
> > 	.../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: in function 'select_next_item'
> > 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:224: in function 'select_next_item'
> > 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:146: in function 'select_next_item'
> > 	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:48: in function 'on_keymap'
> > 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
> > 	....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While performing  on the selection Do you think this is related to this PR or I am looking at the wrong place?
> > Should I open an issue or can I keep commenting on this thread?
> > Edit: I'm using LazyVim distro and haven't changed anything related to cmp on my config
> > Edit2: Confirmation: reverting back to [7e348da](https://github.com/hrsh7th/nvim-cmp/commit/7e348da6e5085ac447144a2ef4b637220ba27209) cleared the issue
> 
> I was just editing my config and trying to figure out where did I f up. This saved hours, thank you.

same, still broken ((

**Comment by Shougo** [comment]
Can you upload your configuration?

**Comment by MichFe** [comment]
> > LGTM.
> 
> ```
> Error  19:23:09 msg_show.emsg E5108: Error executing lua: .../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: attempt to perform arithmetic on local 'cursor' (a nil value)
> stack traceback:
> 	.../nvim/lazy/nvim-cmp/lua/cmp/view/custom_entries_view.lua:328: in function 'select_next_item'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:224: in function 'select_next_item'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:146: in function 'select_next_item'
> 	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/config/mapping.lua:48: in function 'on_keymap'
> 	...monheim/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
> 	....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:127>
> ```
> 
> While performing <C-n> on the selection Do you think this is related to this PR or I am looking at the wrong place?
> 
> Should I open an issue or can I keep commenting on this thread?
> 
> Edit: I'm using LazyVim distro and haven't changed anything related to cmp on my config
> 
> Edit2: Confirmation: reverting back to [7e348da](https://github.com/hrsh7th/nvim-cmp/commit/7e348da6e5085ac447144a2ef4b637220ba27209) cleared the issue

Same issue, after updating nvim-cmp. Solved with a rollback to the mentioned commit, ty for the time saved!

Seems like there may be an issue on the last commit:
        e1757ae feat(view): add api get_selected_index (#1986) (8 hours ago)

**Comment by Shougo** [comment]
@MichFe Please test https://github.com/hrsh7th/nvim-cmp/pull/1993.

**Comment by MichFe** [comment]
> @MichFe Please test #1993.

It is working for me 👍

**Pull request merged**
