### PR TITLE
Fix fuzzy matcher adding invalid matches (#909)

### LINKED ISSUE #909: `col value outside range` with wildmenu
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev+nightly-1651-ga8d5a9e81

### Minimal reproducible full config

not possible ??????

### Description

When I enter `lua print(vim.fn.get_c` I get this:

### Steps to reproduce

-

### Expected behavior

no errors

### Actual behavior

errors

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dansalvato**
Fixes #909 and possibly other occasional issues.

The logic made it possible for non-matches to be inserted to the matches table as a supposed match, which could cause unexpected behavior when views try to render the invalid match. Adding an additional check for `matched` is enough to ensure that only valid matches are added.

### CODE REVIEW

**Comment by hrsh7th** [comment]
@dansalvato Thanks!
Could you provide the reproduction test-case?

I want to add test-case for [this](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/matcher_spec.lua)

**Comment by dansalvato** [comment]
@hrsh7th I came up with a good, succinct way of reproducing this.

Here is my `cmp-repro.vim`:

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'

cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  view = {
    entries = {name = 'wildmenu'}
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
  }, {
    { name = 'buffer' },
  }),
})

cmp.setup({
  experimental = {
  ghost_text = true,
  },
})
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.pyright.setup {
  capabilities = capabilities,
}
EOF
```

Just `nvim -u cmp-repro.vim test.py` and type this:
```py
class TestClass:
    asset_
```

Once you add the underscore to `asset_` while typing, you get the exception.

**Comment by dansalvato** [comment]
Any chance we can move the test-case to an issue and get this merged in the meantime? It's an extremely small change that fixes a longstanding bug but shouldn't have any side effects.

**Comment by hrsh7th** [comment]
I' merge this, but it would be helpful if you could provide test cases.

**Pull request merged**
