### PR TITLE
Fix cmdheight problems

### PR DESCRIPTION
**Pull request by Shougo**
Fix https://github.com/hrsh7th/cmp-cmdline/issues/64.

### CODE REVIEW

**Comment by Shougo** [comment]
Minimal init.vim

```vim
set rtp+=~/src/nvim-cmp
set rtp+=~/src/cmp-buffer
set rtp+=~/src/cmp-nvim-lsp
set rtp+=~/src/vim-vsnip
set rtp+=~/src/cmp-vsnip
set rtp+=~/src/nvim-lspconfig
set rtp+=~/src/cmp-cmdline

set cmdheight=0

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      ['<CR>'] = cmp.mapping.confirm {
        behavior = cmp.ConfirmBehavior.Replace,
        select = true,
      },
      ['<tab>'] = cmp.mapping(cmp.mapping.confirm({ select = true }), { 'i', 's', 'c' }),
      ['<C-p>'] = cmp.mapping.select_prev_item(),
      ['<C-n>'] = cmp.mapping.select_next_item(),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'buffer' },
    },
    completion = {
    completeopt = 'menu,menuone,noselect'
    }
  })
  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'cmdline' }
    }
  })
EOF

lua << EOF
-- Add additional capabilities supported by nvim-cmp
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

--require'lspconfig'.sumneko_lua.setup{}
--require'lspconfig'.cssls.setup{}
--require'lspconfig'.pylsp.setup{}
require'lspconfig'.tailwindcss.setup{}
--require'lspconfig'.gopls.setup{
--  capabilities = capabilities,
--  init_options = {
--    usePlaceholders = true,
--  },
--}
EOF

runtime! after/plugin/*.lua
```

**Comment by gegoune** [comment]
Screenshot 2022-09-27 at 13 55 15

I can get it to such state.

**Comment by Shougo** [comment]
Yes. I know the issue.  So it is not perfect solution.

**Comment by adelarsq** [comment]
It's working:

image

**Comment by laytan** [comment]
Works for me, I do get the same behaviour as https://github.com/hrsh7th/nvim-cmp/pull/1196#issuecomment-1259331184 sometimes but the errors I got regarding nvim-cmp are fixed.

**Comment by Shougo** [comment]
Fixed.

**Comment by gegoune** [comment]
@Shougo Fix confirmed, thank you!

**Comment by laytan** [comment]
Yep, the latest fix works for me too!

**Comment by Shougo** [comment]
I will check the implementation.

**Comment by Shougo** [comment]
I have removed nil checks.  I think it is better.
Please test the patch.

**Comment by laytan** [comment]
Changes still work for me.

**Comment by Shougo** [comment]
@hrsh7th Can you merge it?

**Pull request closed without merging**
