### PR TITLE
Slight complexity reduction

### PR DESCRIPTION
**Pull request by tzachar**
Do not loop twice over sources table, instead keep a table mapping names
to sources

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you. It is a improvement.

**Comment by hrsh7th** [comment]
LGTM! Thank you!

**Comment by hrsh7th** [comment]
Ah. Sorry! It has a side-effect. I will revert it.

**Comment by tzachar** [comment]
What is the side effect? Can it be mitigated?

**Comment by hrsh7th** [comment]
For example, `nvim_lsp` named source can be multiple. (For example, css language server & emmet-ls.)
But this implementation will group the sources by name.

**Pull request merged**
