### PR TITLE
fix: some symbols can't be mapped correctly

### LINKED ISSUE #2080: Can't add Command key(D-/) bindings in MacOS
That's strange because the mapping was working before. I don't know why it suddenly stopped working.
```lua
cmp.setup({
  mapping = {
    -- open / close
    ["<D-/>"] = cmp.mapping({
      i = function()
        if cmp.visible() then
          cmp.abort()
        else
          cmp.complete()
        end
      end,
      c = function()
        if cmp.visible() then
          cmp.close()
        else
          cmp.complete()
        end
      end,
    }),
  },
})
```

### PR DESCRIPTION
**Pull request by OnlyWick**
#1935 will cause some symbols to not be mapped correctly. I have added the symbols that I need to map. I'm not very familiar with others' habits, but I believe there should be some other symbols that need to be added to this patter.

Fix #2080.

### CODE REVIEW

**Review by EasonMo — APPROVED** [review]
Passed the test with <M+/> and can run correctly.

**Review by fell-z — APPROVED** [review]
My keymap `<C-.>` worked correctly.

**Comment by hrsh7th** [comment]
@OnlyWick Could you resolve conflicts?

**Comment by OnlyWick** [comment]
@hrsh7th Done!

**Pull request merged**
