### PR TITLE
Update documentations for config

### PR DESCRIPTION
**Pull request by tzachar**
Add defaults and change wording.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you very much!!!

**Comment by dhruvmanila** [comment]
There are two configuration headers in the README now. I think the first one should be the installation instruction and should the configuration instructions should be removed.

**Comment by tzachar** [comment]
I agree that the first one should read 'Installation Instructions'.
But why remove the second one? It makes no sense to inform users how to configure cmp.

**Comment by dhruvmanila** [comment]
> But why remove the second one? It makes no sense not to inform users how to configure cmp.

Sorry for not to be clear, but I meant to remove the code block after `Then setup configuration. ...` or merge that part into the configuration section.

**Comment by hrsh7th** [comment]
Ah, First one should be `Setup`

**Comment by tzachar** [comment]
Want me to reedit? see #13

**Pull request merged**
