### PR TITLE
fix(view): check in get_selected_index

### PR DESCRIPTION
**Pull request by uga-rosa**
fix error in #1986, maybe

This error does not occur on my end, so I am anticipating and fixing it. I would like to see if this branch will fix it.
@monheimx9, @curiousignite, @0xDmtri, or anyone else.

### CODE REVIEW

**Comment by polirritmico** [comment]
Works for me

**Comment by strottie** [comment]
+1
Works for me too.

**Comment by a3ng7n** [comment]
Works for me as well for #1994 (duplicate of #1988 )

**Comment by telbizov** [comment]
Works for me too!

**Comment by tf42src** [comment]
> You guys are awesome!

Seconding this! Thanks heaps for the quick fix!
🙇

**Comment by monheimx9** [comment]
Working perfectly ᕕ( ᐛ )ᕗ

**Comment by aaronArinder** [comment]
thank you!

**Pull request merged**
