### PR TITLE
Feat: scrollbar option

### PR DESCRIPTION
**Pull request by futsuuu**
Added options to customize the appearance and position of the scrollbars.

For example:

```lua
scrollbar = true,
-- or
scrollbar = {
  thumb_char = " ",
  position = "edge",
},
```

image

---

```lua
scrollbar = {
  thumb_char = "▐",
  position = "inside",
},

-- change hl
```

image

---

```lua
scrollbar = {
  thumb_char = "│",
  position = "edge",
},

-- change hl
```

image

### CODE REVIEW

**Comment by hrsh7th** [comment]
I'll test this PR.

**Comment by futsuuu** [comment]
Thanks.

However, there is a problem at the moment, the scrollbar and the text in the floatwin are covered. So I'm trying to change it so that it changes the width of the floatwin without moving the scrollbars now.

**Comment by ratheesh** [comment]
@futsuuu, Thanks for this PR.
During my usage, I sometimes found discontinuation of scrollbar char like in the image below

image

This does not occur always. Kindly check this

**Comment by ratheesh** [comment]
@futsuuu, May I know why was this PR closed?

**Comment by futsuuu** [comment]
Sorry, but this implementation has several bugs, some of which I can't figure out the cause.
In particular, I think the text wrapping when `position = "inner"` can only be solved with a major internal change.
So, although the functionality to be added will be smaller than this, I will create another PR when I can make a stable one.

**Pull request closed without merging**
